### ISSUE TITLE
Delete function doesn't work

### ISSUE THREAD

**Issue by bernetflorent** [stevecomrie/baserow-php#3]
Hello,
First of all, thank you for your work, it works really well.
I just have an issue for the delete function. It just doesn't work and I always get a 500 error.

I did some research on your project, and I think I found the problem. On your Request.php file, the init function put your "$url_encoded" variable to true in case of a delete. So far so good, but right after, you check if this variable is set to false, and if so you create the json you will send on the cUrl.

Now is the problem. Right after this "if" block (line 129), you wrote:
```
curl_setopt($curl,CURLOPT_POSTFIELDS, json_encode($jsonData));
```
But in the case of a delete, $jsonData doesn't exist because the code didn't go in that "if" block.

I tried 3 solutions that works:

- putting this line inside the "if" block I told about earlier
- modify this line to : 
```
curl_setopt($curl,CURLOPT_POSTFIELDS, json_encode($jsonData ?? []));
```
- initialize you $jsonData at the beginning of the function 

Thanks in advance for your response !

**Comment by stevecomrie** [comment]
Released a new version that should fix this.

Thanks for the report and suggestion.
